version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ./backend:/app
      - /app/venv  # Exclude host Windows virtualenv in container
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude host node_modules in container
    depends_on:
      - backend
    restart: always
